### ISSUE TITLE
Tuturial

### ISSUE THREAD

**Issue by FernandoJBCosta** [giobauermeister/berryE-raspberrypi-robot#1]
Olá Giovanni, estou tentando arrancar este script mas está dando erro.
Estou utilizando um Raspberry pi 3B com o raspbian buster.
Já fiz node app.js e npm start e dá sempre erro.

Pode me ajudar?

Cumprimentos

**Comment by giobauermeister** [comment]
Olá Fernando! :)

Qual é o erro que está ocorrendo?

**Comment by FernandoJBCosta** [comment]
root@jackthebot:/home/pi/workspace-nodejs/berry-e-robot# node app.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'rpio'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/workspace-nodejs/berry-e-robot/app.js:6:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
root@jackthebot:/home/pi/workspace-nodejs/berry-e-robot#

**Comment by FernandoJBCosta** [comment]
Quando instalo o rpio

root@jackthebot:/home/pi/workspace-nodejs/berry-e-robot# npm install rpio

> rpio@0.9.23 install /home/pi/workspace-nodejs/berry-e-robot/node_modules/rpio
> node-gyp rebuild

gyp WARN EACCES current user ("pi") does not have permission to access the dev dir "/root/.cache/node-gyp/8.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/workspace-nodejs/berry-e-robot/node_modules/rpio/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/workspace-nodejs/berry-e-robot/node_modules/rpio/.node-gyp'
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/workspace-nodejs/berry-e-robot/node_modules/rpio
gyp ERR! node -v v8.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN web-fpv@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpio@0.9.23 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpio@0.9.23 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-09T14_09_35_386Z-debug.log
root@jackthebot:/home/pi/workspace-nodejs/berry-e-robot#

**Comment by FernandoJBCosta** [comment]
Tenho de ter uma versão especifica do node js?
Não sou um expert nisso.
Desculpa o incomodo.

**Comment by FernandoJBCosta** [comment]
Olá Giovanni, podes dar uma ajuda?

Obrigado
